proxy_app = "tcp://127.0.0.1:46658"
moniker = "node4"
node_laddr = "tcp://0.0.0.0:46656"
seeds = ""
fast_sync = true
db_backend = "leveldb"
log_level = "notice"
rpc_laddr = "tcp://0.0.0.0:46657"
addrbook_strict=false